# How to do Nonstandard Evaluation in R The Right Way

## or,  `parent.frame` and `match.call` considered evil

However, there are a number of ways in which this assumption breaks down.

## `parent.frame` does **not** find the parent frame

## The parent frame is not where your function's arguments come from

## The parent frame might not even exist any more

### An argument to a function might not be passed from its caller.

### A function might not _have_ a caller any more

It is common to use an argument like `envir=parent.frame()` to provide some additional measure of control to nonstandard-evaluation functions. This has an interesting and tricky interaction with lazy evaluation, however, which can cause `parent.frame()` to drop the ball.

## `match.call` does **not** match the call

To judge from its name and man page, the operational goal of 'match.call' is to return an expression which when evaluated in the caller's environment, recreates, the original function call. This it does not do.

A lovely thing happens when you mix up

## Matching the 

### Examples spotted in the wild

The consequences of a poor approach to nonstandard evaluation are encountered daily on R-help and associated mailing lists. Here are some samples I found.

```
library(ggplot2)
library(plyr)
dlply(diamonds, .(clarity), lm, formula = price ~ carat, subset = cut == 'Ideal')
```
Analysis. `ddply` is not the problem here -- the formula and subset arguments are passed along unevaluated in `...`, and the data argument _should_ be evaluated normally

The problem first appears when `lm` calls a nonstandard-evaluating subfunction, `model.frame,` using this tactic:
```r
    mf <- match.call(expand.dots = FALSE)
    m <- match(c("formula", "data", "subset", "weights", "na.action", 
        "offset"), names(mf), 0L)
    mf <- mf[c(1L, m)]
    mf$drop.unused.levels <- TRUE
    mf[[1L]] <- quote(stats::model.frame)
    mf <- eval(mf, parent.frame())
```

Now, the 'formula' operator, if lm had simply 

## How to work around bad non-standard evaluation in other people's functions

### How to pass arguments to a nonstandard eval function.

The example of `lm` above would 
